### ISSUE TITLE
Transferring external data to another file

### ISSUE THREAD

**Issue by oxcakmak** [ngnducnhat/template-discordjs-v14#2]
Hi, first of all, thank you for sharing your background with me and I must say that it is very successful.

My problem is that when I integrate a multi-language system with YML, I need to get the client value to get the server display language via Mongodb. How can I get this?

![image](https://github.com/ngnducnhat/template-discordjs-v14/assets/48910999/7de85a60-e7d0-411e-b3d9-87dac3841339)

utils/localization.js:
```
const YAML = require("js-yaml");
const fs = require("fs");

let language = "en";

function _(data, props) {
  const filePath = `locales/${language}.yml`;

  // Ensure data is a string and language is defined
  if (!data || typeof data !== "string") {
    return data;
  }

  try {
    // Read YAML file and parse data
    const fileData = fs.readFileSync(filePath, "utf8");
    const langData = YAML.load(fileData);

    // Regular expression to match placeholders within double curly braces
    const regex = /\{\{([^\}]+)\}\}/g;

    // Check if data contains placeholders and replace them with values
    if (langData[data])
      return langData[data].replace(regex, (match, key) => {
        return props[key] !== undefined ? props[key] : match; // Replace with value or fallback
      });

    return data; // Return original data if key not found in YAML
  } catch (error) {
    console.error(
      `Error loading translations for language ${language}:`,
      error
    );
    return data; // Handle errors by returning original data
  }
}

module.exports = { _ };
```

index.js
```
const {
  Client,
  GatewayIntentBits,
  Partials,
  Collection,
} = require("discord.js");

const { Guilds, GuildMembers, GuildMessages } = GatewayIntentBits;
const { User, Message, GuildMember, ThreadMember } = Partials;

//events and commands
const { loadEvents } = require("./handlers/eventHandler");
const { loadCommands } = require("./handlers/commandHandler");
const { loadDatabase } = require("./handlers/databaseHandler");
const { loadUtils } = require("./handlers/utilsHandler");

//get token
const { token } = require("./config.json");

const client = new Client({
  intents: [Guilds, GuildMembers, GuildMessages],
  partials: [User, Message, GuildMember, ThreadMember],
});

client.commands = new Collection();

//login
client.login(token).then(() => {
  loadEvents(client);
  loadCommands(client);
  loadDatabase();
  loadUtils();
});
```

Regards.

**Comment by ngducnhatt** [comment]
First of all, thank you for your interest in my project. As far as I can see, in the project I do not use the language command, but if you want you can create some json files for example: en.json, vi.json…. right in your project and use require to get and use directly. You should do that because when you want to get data from mongodb you will have to do additional GET operations so your BOT processing speed will be slower. If you still want to use MongoDB, search for "how to connect MongoDB" and follow. Good luck🤍

**Comment by oxcakmak** [comment]
Thank you for your answer, but it seems that you don't fully understand my problem. 

My problem is localizing the server id.how can I send it to the js file?

I already have a column called displayLanguage in the Configurations table in mongo db.  If I pull the server ids in some way, I can simply query it via mongo.

**Comment by oxcakmak** [comment]
i fixed solution the easiest way. require(file).{function()}
